import type { TemplateDefinition } from "@/types/builder";
import { baseTheme } from "./website-defaults";

const t = baseTheme();

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: "minimal-portfolio",
    name: "Minimal Portfolio",
    category: "Portfolio",
    description: "A clean, editorial portfolio for developers and designers. Quiet type, generous whitespace.",
    tags: ["minimal", "developer", "designer", "resume"],
    style: "Minimal",
    mode: "light",
    tier: "free",
    thumbnailGradient: "#f1efe9",
    theme: { ...t, primary: "#111111", background: "#ffffff", surface: "#f6f6f5", text: "#111111", muted: "#6b7280", accent: "#111111", fontHeading: "Inter", fontBody: "Inter", radius: 10 },
    sections: [
      { type: "navbar", variant: "minimal" },
      { type: "hero", variant: "split" },
      { type: "about", variant: "simple" },
      { type: "skills", variant: "bars" },
      { type: "projects", variant: "grid" },
      { type: "experience", variant: "timeline" },
      { type: "contact", variant: "minimal" },
      { type: "footer", variant: "simple" },
    ],
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    category: "Photography",
    description: "Bold poster-style layout for photographers and visual artists. Full-bleed type, dark feature gallery.",
    tags: ["photography", "gallery", "artist", "visual"],
    style: "Bold",
    mode: "dark",
    tier: "free",
    thumbnailGradient: "#141414",
    theme: { ...t, primary: "#18181b", secondary: "#a1a1aa", background: "#0c0c0c", surface: "#1c1c1f", text: "#fafafa", muted: "#a1a1aa", accent: "#e7e5e4", fontHeading: "Fraunces", fontBody: "Inter", radius: 4 },
    sections: [
      { type: "navbar", variant: "overlay" },
      { type: "hero", variant: "poster" },
      { type: "gallery", variant: "feature" },
      { type: "about", variant: "editorial" },
      { type: "testimonials", variant: "quote" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "big" },
    ],
  },
  {
    id: "professional-business",
    name: "Consultant Pro",
    category: "Business",
    description: "Trust-building business site for consultants and professional services. Calm navy, clear proof.",
    tags: ["consulting", "services", "corporate", "agency"],
    style: "Corporate",
    mode: "light",
    tier: "free",
    thumbnailGradient: "#e3ecf5",
    theme: { ...t, primary: "#1e3a5f", secondary: "#475569", background: "#ffffff", surface: "#f1f5f9", text: "#0f172a", muted: "#64748b", accent: "#2563eb", fontHeading: "Plus Jakarta Sans", fontBody: "Inter", radius: 8 },
    sections: [
      { type: "navbar", variant: "solid" },
      { type: "hero", variant: "editorial" },
      { type: "services", variant: "list" },
      { type: "process", variant: "steps" },
      { type: "testimonials", variant: "cards" },
      { type: "pricing", variant: "tiers" },
      { type: "faq", variant: "accordion" },
      { type: "cta", variant: "banner" },
      { type: "footer", variant: "columns" },
    ],
  },
  {
    id: "restaurant",
    name: "Ember & Oak",
    category: "Restaurant",
    description: "Warm, appetite-first restaurant site with centered masthead, menu, hours and reservations.",
    tags: ["food", "menu", "hospitality", "local"],
    style: "Warm",
    mode: "light",
    tier: "free",
    thumbnailGradient: "#f7e8d3",
    theme: { ...t, primary: "#7c2d12", secondary: "#9a3412", background: "#fffdf7", surface: "#fef3e8", text: "#292019", muted: "#8a7a6b", accent: "#ea580c", fontHeading: "Fraunces", fontBody: "Inter", radius: 12 },
    sections: [
      { type: "navbar", variant: "centered" },
      { type: "hero", variant: "image" },
      { type: "about", variant: "card" },
      { type: "menu", variant: "grouped" },
      { type: "gallery", variant: "grid" },
      { type: "hours", variant: "card" },
      { type: "testimonials", variant: "minimal" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "minimal" },
    ],
  },
  {
    id: "agency",
    name: "Studio Himal",
    category: "Agency",
    description: "Confident agency site with services, process, team and case work. Built to win clients.",
    tags: ["agency", "studio", "startup", "saas"],
    style: "Modern",
    mode: "light",
    tier: "premium",
    thumbnailGradient: "#e4e0f5",
    theme: { ...t, primary: "#111111", secondary: "#4b5563", background: "#ffffff", surface: "#f5f5f4", text: "#111111", muted: "#6b7280", accent: "#7c3aed", fontHeading: "Space Grotesk", fontBody: "Inter", radius: 14 },
    sections: [
      { type: "navbar", variant: "bold" },
      { type: "hero", variant: "poster" },
      { type: "services", variant: "split" },
      { type: "projects", variant: "editorial" },
      { type: "process", variant: "steps" },
      { type: "team", variant: "grid" },
      { type: "testimonials", variant: "grid" },
      { type: "cta", variant: "banner" },
      { type: "footer", variant: "big" },
    ],
  },
  {
    id: "saas-starter",
    name: "Sajilo",
    category: "SaaS",
    description: "Crisp SaaS marketing page with pricing, FAQ and a strong call to action.",
    tags: ["saas", "startup", "product", "landing"],
    style: "Modern",
    mode: "light",
    tier: "premium",
    thumbnailGradient: "#ddefe6",
    theme: { ...t, primary: "#064e3b", secondary: "#047857", background: "#ffffff", surface: "#ecfdf5", text: "#0b1f17", muted: "#5f7267", accent: "#10b981", fontHeading: "Plus Jakarta Sans", fontBody: "Inter", radius: 12 },
    sections: [
      { type: "navbar", variant: "solid" },
      { type: "hero", variant: "split" },
      { type: "logos", variant: "row" },
      { type: "services", variant: "cards" },
      { type: "projects", variant: "list" },
      { type: "pricing", variant: "tiers" },
      { type: "faq", variant: "accordion" },
      { type: "cta", variant: "banner" },
      { type: "footer", variant: "columns" },
    ],
  },
  {
    id: "freelancer",
    name: "Solo",
    category: "Freelancer",
    description: "Rate-card portfolio for independent designers and developers. Day rates, work log, booking.",
    tags: ["freelance", "solo", "rates", "booking"],
    style: "Ledger",
    mode: "light",
    tier: "free",
    thumbnailGradient: "#e2e9e0",
    theme: { ...t, primary: "#0f5132", secondary: "#3f6212", background: "#fdfcf8", surface: "#f0ede3", text: "#14231b", muted: "#6b7a6f", accent: "#c2410c", fontHeading: "Inter", fontBody: "Inter", radius: 10 },
    sections: [
      { type: "navbar", variant: "minimal" },
      { type: "hero", variant: "split" },
      { type: "services", variant: "list" },
      { type: "projects", variant: "grid" },
      { type: "testimonials", variant: "minimal" },
      { type: "pricing", variant: "tiers" },
      { type: "contact", variant: "minimal" },
      { type: "footer", variant: "simple" },
    ],
  },
  {
    id: "event",
    name: "Utsav",
    category: "Event",
    description: "Loud festival site with lineup, running order, ticket stubs and venue info.",
    tags: ["festival", "concert", "tickets", "lineup"],
    style: "Festive",
    mode: "light",
    tier: "premium",
    thumbnailGradient: "#2e1065",
    theme: { ...t, primary: "#2e1065", secondary: "#6d28d9", background: "#faf8ff", surface: "#efe9fb", text: "#1e1332", muted: "#7a7291", accent: "#d4a017", fontHeading: "Plus Jakarta Sans", fontBody: "Inter", radius: 12 },
    sections: [
      { type: "navbar", variant: "solid" },
      { type: "hero", variant: "poster" },
      { type: "gallery", variant: "masonry" },
      { type: "logos", variant: "row" },
      { type: "process", variant: "steps" },
      { type: "team", variant: "grid" },
      { type: "pricing", variant: "tiers" },
      { type: "faq", variant: "accordion" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "columns" },
    ],
  },
  {
    id: "wedding",
    name: "Bihe",
    category: "Wedding",
    description: "Romantic wedding site with story, events, gallery and an RSVP form that counts thalis.",
    tags: ["wedding", "bihe", "rsvp", "events", "family"],
    style: "Romantic",
    mode: "light",
    tier: "free",
    thumbnailGradient: "#f6dfe2",
    theme: { ...t, primary: "#7f1d2e", secondary: "#b76e79", background: "#fffdf9", surface: "#faf3ea", text: "#3d2229", muted: "#9a7f86", accent: "#e11d48", fontHeading: "Fraunces", fontBody: "Inter", radius: 14 },
    sections: [
      { type: "navbar", variant: "centered" },
      { type: "hero", variant: "poster" },
      { type: "banner", variant: "strip" },
      { type: "about", variant: "simple" },
      { type: "gallery", variant: "feature" },
      { type: "process", variant: "steps" },
      { type: "testimonials", variant: "quote" },
      { type: "faq", variant: "accordion" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "minimal" },
    ],
  },
  {
    id: "fitness",
    name: "Forge",
    category: "Fitness",
    description: "Brutalist gym site with volt-on-charcoal attitude, plans, coaches and a free-week offer.",
    tags: ["gym", "fitness", "coaches", "membership", "training"],
    style: "Brutal",
    mode: "dark",
    tier: "free",
    thumbnailGradient: "#141412",
    theme: { ...t, primary: "#1c1c19", secondary: "#9aa39a", background: "#121210", surface: "#1f1f1b", text: "#f2f5ee", muted: "#9aa39a", accent: "#e4572e", fontHeading: "Space Grotesk", fontBody: "Inter", radius: 4 },
    sections: [
      { type: "navbar", variant: "bold" },
      { type: "banner", variant: "dark" },
      { type: "hero", variant: "poster" },
      { type: "stats", variant: "band" },
      { type: "pricing", variant: "tiers" },
      { type: "team", variant: "grid" },
      { type: "gallery", variant: "grid" },
      { type: "faq", variant: "accordion" },
      { type: "cta", variant: "banner" },
      { type: "footer", variant: "big" },
    ],
  },
  {
    id: "coffee",
    name: "Copper Cup",
    category: "Café",
    description: "Warm neighbourhood café site with brew board, hours and a story worth sipping.",
    tags: ["cafe", "coffee", "menu", "chiya", "bakery"],
    style: "Craft",
    mode: "light",
    tier: "free",
    thumbnailGradient: "#efe0c8",
    theme: { ...t, primary: "#4a2c1a", secondary: "#a0714f", background: "#faf6ef", surface: "#f1e7d6", text: "#2b1d12", muted: "#8a7663", accent: "#c2703d", fontHeading: "Fraunces", fontBody: "Inter", radius: 12 },
    sections: [
      { type: "navbar", variant: "centered" },
      { type: "hero", variant: "image" },
      { type: "menu", variant: "grouped" },
      { type: "hours", variant: "card" },
      { type: "gallery", variant: "grid" },
      { type: "testimonials", variant: "minimal" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "minimal" },
    ],
  },
  {
    id: "real-estate",
    name: "Haven",
    category: "Real Estate",
    description: "Boutique brokerage site with featured listings, track record and agents who pick up.",
    tags: ["real estate", "homes", "land", "rentals", "agents"],
    style: "Trust",
    mode: "light",
    tier: "free",
    thumbnailGradient: "#dde0d2",
    theme: { ...t, primary: "#1d3b2a", secondary: "#5c6e60", background: "#fbfaf7", surface: "#eef0e9", text: "#14201a", muted: "#6b7568", accent: "#b98a2f", fontHeading: "Plus Jakarta Sans", fontBody: "Inter", radius: 10 },
    sections: [
      { type: "navbar", variant: "solid" },
      { type: "hero", variant: "split" },
      { type: "gallery", variant: "feature" },
      { type: "stats", variant: "band" },
      { type: "services", variant: "list" },
      { type: "testimonials", variant: "cards" },
      { type: "team", variant: "grid" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "columns" },
    ],
  },
  {
    id: "detailing",
    name: "Chamak",
    category: "Automotive",
    description: "Mobile detailing studio with proof-of-work gallery, packages and booking that comes to you.",
    tags: ["car", "detailing", "automotive", "booking", "services"],
    style: "Gloss",
    mode: "dark",
    tier: "free",
    thumbnailGradient: "#1a222b",
    theme: { ...t, primary: "#232a31", secondary: "#9aa7b4", background: "#14171c", surface: "#1f262e", text: "#eef2f6", muted: "#9aa7b4", accent: "#e0a32e", fontHeading: "Space Grotesk", fontBody: "Inter", radius: 10 },
    sections: [
      { type: "navbar", variant: "bold" },
      { type: "banner", variant: "dark" },
      { type: "hero", variant: "poster" },
      { type: "stats", variant: "band" },
      { type: "services", variant: "cards" },
      { type: "pricing", variant: "tiers" },
      { type: "gallery", variant: "feature" },
      { type: "process", variant: "steps" },
      { type: "testimonials", variant: "cards" },
      { type: "faq", variant: "accordion" },
      { type: "cta", variant: "banner" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "big" },
    ],
  },
];
export function getTemplate(id: string) {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}

export const CATEGORIES = ["All", ...Array.from(new Set(TEMPLATES.map((t) => t.category)))];
