import type { TemplateDefinition } from "@/types/builder";
import { baseTheme } from "./website-defaults";

const t = baseTheme();

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: "minimal-portfolio",
    name: "Minimal Portfolio",
    category: "Portfolio",
    description: "A clean, editorial portfolio for developers and designers. Quiet type, generous whitespace.",
    tags: ["minimal", "developer", "designer", "resume"],
    style: "Minimal",
    mode: "light",
    tier: "free",
    thumbnailGradient: "linear-gradient(135deg,#fafafa,#e7e5e4)",
    theme: { ...t, primary: "#111111", background: "#ffffff", surface: "#f6f6f5", text: "#111111", muted: "#6b7280", accent: "#111111", fontHeading: "Inter", fontBody: "Inter", radius: 10 },
    sections: [
      { type: "navbar", variant: "minimal" },
      { type: "hero", variant: "split" },
      { type: "about", variant: "simple" },
      { type: "skills", variant: "bars" },
      { type: "projects", variant: "grid" },
      { type: "experience", variant: "timeline" },
      { type: "contact", variant: "minimal" },
      { type: "footer", variant: "simple" },
    ],
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    category: "Photography",
    description: "Bold poster-style layout for photographers and visual artists. Full-bleed type, dark feature gallery.",
    tags: ["photography", "gallery", "artist", "visual"],
    style: "Bold",
    mode: "dark",
    tier: "free",
    thumbnailGradient: "linear-gradient(135deg,#0a0a0a,#3b2f2f)",
    theme: { ...t, primary: "#18181b", secondary: "#a1a1aa", background: "#0c0c0c", surface: "#1c1c1f", text: "#fafafa", muted: "#a1a1aa", accent: "#e7e5e4", fontHeading: "Fraunces", fontBody: "Inter", radius: 4 },
    sections: [
      { type: "navbar", variant: "overlay" },
      { type: "hero", variant: "poster" },
      { type: "gallery", variant: "feature" },
      { type: "about", variant: "editorial" },
      { type: "testimonials", variant: "quote" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "big" },
    ],
  },
  {
    id: "professional-business",
    name: "Consultant Pro",
    category: "Business",
    description: "Trust-building business site for consultants and professional services. Calm navy, clear proof.",
    tags: ["consulting", "services", "corporate", "agency"],
    style: "Corporate",
    mode: "light",
    tier: "free",
    thumbnailGradient: "linear-gradient(135deg,#eff6ff,#dbeafe)",
    theme: { ...t, primary: "#1e3a5f", secondary: "#475569", background: "#ffffff", surface: "#f1f5f9", text: "#0f172a", muted: "#64748b", accent: "#2563eb", fontHeading: "Plus Jakarta Sans", fontBody: "Inter", radius: 8 },
    sections: [
      { type: "navbar", variant: "solid" },
      { type: "hero", variant: "editorial" },
      { type: "services", variant: "list" },
      { type: "process", variant: "steps" },
      { type: "testimonials", variant: "cards" },
      { type: "pricing", variant: "tiers" },
      { type: "faq", variant: "accordion" },
      { type: "cta", variant: "banner" },
      { type: "footer", variant: "columns" },
    ],
  },
  {
    id: "restaurant",
    name: "Ember & Oak",
    category: "Restaurant",
    description: "Warm, appetite-first restaurant site with centered masthead, menu, hours and reservations.",
    tags: ["food", "menu", "hospitality", "local"],
    style: "Warm",
    mode: "light",
    tier: "free",
    thumbnailGradient: "linear-gradient(135deg,#fffbeb,#fed7aa)",
    theme: { ...t, primary: "#7c2d12", secondary: "#9a3412", background: "#fffdf7", surface: "#fef3e8", text: "#292019", muted: "#8a7a6b", accent: "#ea580c", fontHeading: "Fraunces", fontBody: "Inter", radius: 12 },
    sections: [
      { type: "navbar", variant: "centered" },
      { type: "hero", variant: "image" },
      { type: "about", variant: "card" },
      { type: "menu", variant: "grouped" },
      { type: "gallery", variant: "grid" },
      { type: "hours", variant: "card" },
      { type: "testimonials", variant: "minimal" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "minimal" },
    ],
  },
  {
    id: "agency",
    name: "Studio Himal",
    category: "Agency",
    description: "Confident agency site with services, process, team and case work. Built to win clients.",
    tags: ["agency", "studio", "startup", "saas"],
    style: "Modern",
    mode: "light",
    tier: "premium",
    thumbnailGradient: "linear-gradient(135deg,#f5f3ff,#ddd6fe)",
    theme: { ...t, primary: "#111111", secondary: "#4b5563", background: "#ffffff", surface: "#f5f5f4", text: "#111111", muted: "#6b7280", accent: "#7c3aed", fontHeading: "Space Grotesk", fontBody: "Inter", radius: 14 },
    sections: [
      { type: "navbar", variant: "bold" },
      { type: "hero", variant: "poster" },
      { type: "services", variant: "split" },
      { type: "projects", variant: "editorial" },
      { type: "process", variant: "steps" },
      { type: "team", variant: "grid" },
      { type: "testimonials", variant: "grid" },
      { type: "cta", variant: "banner" },
      { type: "footer", variant: "big" },
    ],
  },
  {
    id: "saas-starter",
    name: "Sajilo",
    category: "SaaS",
    description: "Crisp SaaS marketing page with pricing, FAQ and a strong call to action.",
    tags: ["saas", "startup", "product", "landing"],
    style: "Modern",
    mode: "light",
    tier: "premium",
    thumbnailGradient: "linear-gradient(135deg,#ecfdf5,#d1fae5)",
    theme: { ...t, primary: "#064e3b", secondary: "#047857", background: "#ffffff", surface: "#ecfdf5", text: "#0b1f17", muted: "#5f7267", accent: "#10b981", fontHeading: "Plus Jakarta Sans", fontBody: "Inter", radius: 12 },
    sections: [
      { type: "navbar", variant: "solid" },
      { type: "hero", variant: "split" },
      { type: "logos", variant: "row" },
      { type: "services", variant: "cards" },
      { type: "projects", variant: "list" },
      { type: "pricing", variant: "tiers" },
      { type: "faq", variant: "accordion" },
      { type: "cta", variant: "banner" },
      { type: "footer", variant: "columns" },
    ],
  },
  {
    id: "freelancer",
    name: "Solo",
    category: "Freelancer",
    description: "Rate-card portfolio for independent designers and developers. Day rates, work log, booking.",
    tags: ["freelance", "solo", "rates", "booking"],
    style: "Ledger",
    mode: "light",
    tier: "free",
    thumbnailGradient: "linear-gradient(135deg,#f0f7f2,#d7e8dc)",
    theme: { ...t, primary: "#0f5132", secondary: "#3f6212", background: "#fdfcf8", surface: "#f0ede3", text: "#14231b", muted: "#6b7a6f", accent: "#c2410c", fontHeading: "Inter", fontBody: "Inter", radius: 10 },
    sections: [
      { type: "navbar", variant: "minimal" },
      { type: "hero", variant: "split" },
      { type: "services", variant: "list" },
      { type: "projects", variant: "grid" },
      { type: "testimonials", variant: "minimal" },
      { type: "pricing", variant: "tiers" },
      { type: "contact", variant: "minimal" },
      { type: "footer", variant: "simple" },
    ],
  },
  {
    id: "event",
    name: "Utsav",
    category: "Event",
    description: "Loud festival site with lineup, running order, ticket stubs and venue info.",
    tags: ["festival", "concert", "tickets", "lineup"],
    style: "Festive",
    mode: "light",
    tier: "premium",
    thumbnailGradient: "linear-gradient(135deg,#2e1065,#7c3aed)",
    theme: { ...t, primary: "#2e1065", secondary: "#6d28d9", background: "#faf8ff", surface: "#efe9fb", text: "#1e1332", muted: "#7a7291", accent: "#d4a017", fontHeading: "Plus Jakarta Sans", fontBody: "Inter", radius: 12 },
    sections: [
      { type: "navbar", variant: "solid" },
      { type: "hero", variant: "poster" },
      { type: "gallery", variant: "masonry" },
      { type: "logos", variant: "row" },
      { type: "process", variant: "steps" },
      { type: "team", variant: "grid" },
      { type: "pricing", variant: "tiers" },
      { type: "faq", variant: "accordion" },
      { type: "contact", variant: "split" },
      { type: "footer", variant: "columns" },
    ],
  },
];

export function getTemplate(id: string) {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}

export const CATEGORIES = ["All", ...Array.from(new Set(TEMPLATES.map((t) => t.category)))];
